# Generated by Django 5.0.1 on 2024-01-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('role', models.CharField(max_length=200)),
                ('results', models.TextField()),
                ('date_or_duration', models.CharField(max_length=100)),
                ('technologies', models.CharField(max_length=200)),
                ('team_members', models.TextField(blank=True)),
                ('project_link', models.URLField(blank=True)),
                ('repository_link', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
            ],
        ),
    ]
