# Generated by Django 5.0.1 on 2024-01-20 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('content', models.TextField()),
                ('excerpt', models.TextField()),
                ('categories', models.CharField(blank=True, max_length=200)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
