# Generated by Django 5.0.1 on 2024-01-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_message', models.TextField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='home_bg_images/')),
                ('additional_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
