# Generated by Django 5.0.1 on 2024-01-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepage_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
