# Generated by Django 5.0.1 on 2024-01-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='publications/media/publication_pdfs/'),
        ),
    ]
