# Generated by Django 5.0.1 on 2024-01-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('description', models.TextField()),
                ('technologies', models.CharField(max_length=200)),
                ('date_or_duration', models.CharField(max_length=100)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('case_study_link', models.URLField(blank=True)),
            ],
        ),
    ]
